name: CI

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build the project
        run: pnpm build

  typecheck:
    name: Type Check

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Type check the project
        run: pnpm typecheck

  lint:
    name: Lint

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Check code styles
        run: pnpm lint

  knip:
    name: Knip

    runs-on: ubuntu-latest

    timeout-minutes: 30

    continue-on-error: true

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Check dead code/dependency
        run: pnpm knip

  test:
    name: Test

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run unit tests
        run: pnpm test:coverage

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v7
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: typescript-monorepo-org/typescript-monorepo-template
